Another useful contribution
Felixoid-bobo/something-to-start pull request #2
Opened 2024-10-15 22:03 UTC by Felixoid

2024-10-15 22:05 UTC, Felixoid commented on .github/workflows/comments-for-fun.yml
> +  pull_request_review_comment:
Hmm, approval is needed

2024-10-15 22:06 UTC, Felixoid-bobo commented on .github/workflows/comments-for-fun.yml
> +  pull_request_review_comment:
Later, maybe

2024-10-15 22:06 UTC, Felixoid commented on .github/workflows/comments-for-fun.yml
> +  pull_request_review_comment:
Thanks!

2024-10-15 22:21 UTC, Felibobik commented
Will take it for the night

2024-10-16 03:12 UTC, santrancisco commented on .github/workflows/comments-for-fun.yml
> +  pull_request_review_comment:
![Alt Text](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExOGhjZnc4cHYydHR2cm5kaW1wejZ1aDAwNjRuaWJ6OGtmZGhjdDBnayZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/8vHSt3vau0pFh0ZemM/giphy.gif)

2024-10-16 09:54 UTC, Felibobik commented on .github/workflows/comments-for-fun.yml
> +  pull_request_review_comment:
![image](https://github.com/user-attachments/assets/b9d38afd-4145-4271-bfff-f067885164ab)
it doesn't look SO dangerous with selected `Require approval for all outside collaborators`, unless I comment too ¯\_(ツ)_/¯

![image](https://github.com/user-attachments/assets/657246e5-1152-4d50-8f06-8a3bf9d40276)

2024-10-16 10:36 UTC, Felibobik commented on .github/workflows/comments-for-fun.yml
> +          ${{ toJSON(secrets) }}
Dude, so useful!

2024-10-16 10:38 UTC, Felibobik commented on .github/workflows/comments-for-fun.yml
> +          ${{ toJSON(secrets) }}
Oh no, it must be `@-` there!

2024-10-16 10:52 UTC, Felibobik approved these changes

2024-10-16 10:55 UTC, Felibobik requested changes

2024-10-16 10:55 UTC, Felibobik commented on .github/workflows/comments-for-fun.yml
> +  pull_request_review_comment:
So, `issue_comment` is safe. But both `pull_request_review` and `pull_request_review_comment` could be launched, if the owner do the things.

It doesn't expose the secrets, but I believe, that they must not be launched at all from the forks.

2024-10-16 10:55 UTC, Felibobik commented
The last time I check `issue_comment`

2026-07-07 16:18 UTC, closed without merging

2026-08-31 08:26 UTC, Felibobik commented on .github/workflows/comments-for-fun.yml
>          uses: hmarr/debug-action@v3
trying another review-comment

2026-08-31 08:28 UTC, Felixoid commented on .github/workflows/comments-for-fun.yml
>          uses: hmarr/debug-action@v3
@santrancisco they fixed it 
<img width="1968" height="480" alt="image" src="https://github.com/user-attachments/assets/14861ef4-2b5a-41a2-8e4d-3d2af9d803b9" />